sudo: false
language: node_js
node_js:
  - "6.3"

notifications:
  email: true

branches:
  only:
    - master

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/createMap.d/xvfb start
  - sleep 3
